/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.ui.contentassist;

import org.xtext.example.mydsl1.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
