/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.book1.ui.internal.Book1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Book1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Book1Activator.getInstance().getInjector(Book1Activator.ORG_XTEXT_EXAMPLE_MYDSL1_MYDSL);
	}
	
}
